name: flutter_scraping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  html: ^0.15.4
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  flutter_displaymode: ^0.6.0
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  permission_handler: ^10.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
