name: flutter_scraping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  html: ^0.15.4
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  flutter_cache_manager: ^3.3.1
  provider: ^6.0.5
  shared_preferences: ^2.3.4
  dio: ^5.3.3
  archive: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
